import { Metadata } from 'next'
import MainProvider from 'providers/MainProvider'
import 'react-redux-toastr/lib/css/react-redux-toastr.min.css'

import Navigation from '@/components/navigation/Navigation'
import Sidebar from '@/components/sidebar/Sidebar'

import '@/assets/styles/react-select.scss'

import '../assets/styles/globals.scss'

import styles from './layout.module.scss'

export const metadata: Metadata = {
	icons: {
		icon: '/src/assets/images/logo.svg',
	},
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	debugger
	return (
		<html lang="en">
			<body>
				<MainProvider>
					<div className={styles.layout}>
						<Navigation />
						<main className={styles.center}>{children}</main>
						<Sidebar />
					</div>
				</MainProvider>
			</body>
		</html>
	)
}
